name: Deploy
on:
  workflow_dispatch:


jobs:
  deploy:
    environment: Actions
    strategy:
      matrix:
        arch: ["x86_64", "arm64"]
        os: [ubunbu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      platform: macos
      CONDA_PLATFORM: MacOSX
      build_type: ${{ matrix.build_type }}
      arch: ${{ matrix.arch }}
      shared_suffix: "dylib"
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/bootstrap.sh
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.11.1.1208 # Clojure CLI based on tools.deps
      - name: Install dependencies
        run: clojure -P
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -X:export

