name: Deploy webgpu-native
on:
  workflow_dispatch:

env:
  version: "v0.19.4.1"

jobs:
  deploy:
    environment: Actions
    runs-on: "ubuntu-latest"
    env:
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.11.1.1208 # Clojure CLI based on tools.deps
      - name: Install dependencies
        run: clojure -P
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -M:project -m com.phronemophobic.cljonda.webgpu-native ${{ env.version }}

