name: Deploy automerge
on:
  workflow_dispatch:

env:
  commit: "a11222254d2f86ec9df0738e7002f15a930fe9b4"


          # - os: "macos-latest"
          #   arch: "x64"

jobs:
  deploy:
    environment: Actions
    strategy:
      matrix:
        include:
          - os: "macos-14"
            osname: "macos"
            arch: "aarch64"
          - os: "ubuntu-latest"
            osname: "ubuntu
            arch: "x64"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install packages
        if: matrix.os == 'ubuntu'
        run: sudo apt-get update -y && sudo apt-get install patchelf cmocka-doc libcmocka-dev -y
      - name: Install build dependencies
        if: matrix.osname == 'macos'
        run: |
          brew install cmocka
          rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          architecture: ${{ matrix.arch }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.6.1
        with:
          # Install just one or all simultaneously
          cli: 1.12.5.1654 # Clojure CLI based on tools.deps
      - name: Install dependencies
        run: clojure -P
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -M:project -m com.phronemophobic.cljonda.libautomerge ${{ env.commit }}

