name: Deploy stable-diffusion
on:
  workflow_dispatch:

env:
  commit: "9c51d8787f78ef1bd0ead1e8f48b766d7ee7484d"

jobs:
  deploy:
    environment: Actions
    strategy:
      matrix:
        include:
          - os: "macos-14"
            arch: "aarch64"
          - os: "macos-latest"
            arch: "x64"
          # - os: "ubuntu-latest"
          #   arch: "x64"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          architecture: ${{ matrix.arch }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.11.1.1208 # Clojure CLI based on tools.deps
      - name: Install dependencies
        run: clojure -P
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -M:project -m com.phronemophobic.cljonda.stable-diffusion ${{ env.commit }}

